### ISSUE TITLE
Merge filter generalizable?

### ISSUE THREAD

**Issue by jessakay** [ay-lab/fithic#27]
Having multiple adjacent bin pairs all passing some constant significance threshold despite stemming from the same underlying interaction can be an issue in quite a number of other Hi-C analyses, for instance in calling differential interactions by SELFISH as implemented by your group.

The merging filer introduced here seems like a nice approach to this problem, but I was curious if there has been any testing done on whether such a method is suited to prune the output of other tools?

Thanks!

**Comment by ay-lab** [comment]
Hi, yes, the idea and any other similar approach for local filtering can
and should be applicable to other Hi-C analyses as you are suggesting.
However, for SELFISH and for a new tool we recently released (Mustache)
this would not be needed at all because they already handle the dependency
between neighboring pixels and implement their own local filters. We
haven't tried but it is very likely that the merging filter will make no
difference at all in their results.
Thanks for the suggestion.
