### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by sunthink** [ay-lab/fithic#39]
Hi,
I am running version Fit-Hi-C 2.0.7.

The input files look like this:
![image](https://user-images.githubusercontent.com/13810375/103396567-f5f6a580-4b6e-11eb-8862-9b2df53adb0b.png)
![image](https://user-images.githubusercontent.com/13810375/103396559-eaa37a00-4b6e-11eb-961a-a269e6168a1e.png)
![image](https://user-images.githubusercontent.com/13810375/103396547-deb7b800-4b6e-11eb-9368-8460abcb4df9.png)

I used the command below
fithic -i fithic.interactionCounts.gz -f fithic.fragmentMappability.gz -t fithic.biases.gz -r 5000 -x intraOnly -U 5000000 -L 20000 -o ./23_10k -l 23_10k-intrachrom -v

and encounter the error
![image](https://user-images.githubusercontent.com/13810375/103396385-f3e01700-4b6d-11eb-96be-21a7d9b17238.png)

When I just extracted one chromosome infomation from the three files to new files, and run the same command, it works. 

Please help me out.
Thank you in advance for your help,
Chengming

**Comment by ay-lab** [comment]
Others have experienced similar problems if you look at the previous posts. It is likely because you have a scaffold or a chromosome that has all its fragments with bias values outside the range. Maybe we should put a specific warning for this. Just check to see which are scaffolds with bias values all less than 0.5 or above 2. Also, seems like your bias values are quite off in general, their average should be 1, yours are very small. Make sure to rescale them if this is the case.

**Comment by sunthink** [comment]
Thanks for your reply. 

After removing these short length scaffolds with  bias values all less than 0.5, fit-hic2 works.

**Comment by 41622236** [comment]
Hi,everyone!
I also encountered this problem. But I still don't know how to solve it, can anyone help me ?

Thanks!
