### ISSUE TITLE
Missing chr1 in output

### ISSUE THREAD

**Issue by GRGong** [ay-lab/fithic#44]
Hi,
  Thanks for the magic tool. But, I can't find either inter or intra-chromosome data related with chr1 in the output file. I wonder how to fix that.

**Comment by ay-lab** [comment]
Hi, without seeing the data I can only guess. One possibility is that there is a copy number difference between chr1 and other chrs so that chr1 counts never reach significance. You may want to look at 1D coverage values of chr1 compared to others. Or visualize chr1 contact map together with another chrs using the same exact color scale.
